name: 'mdbook setup action'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Setup cargo-make
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-make
    - uses: cargo-bins/cargo-binstall@main
    - name: Install mdbook
      shell: bash
      run: cargo binstall mdbook@0.5.1 mdbook-toc@0.15.1 mdbook-open-on-gh@3.0.0
    - name: Setup mdbook-katex
      shell: bash
      run: |
        mkdir -p mdbook-katex
        cd mdbook-katex
        curl -L https://github.com/lzanini/mdbook-katex/releases/download/0.10.0-alpha-binaries/mdbook-katex-v0.10.0-alpha-x86_64-unknown-linux-gnu.tar.gz -o mdbook-katex.tar.gz
        tar -xvf mdbook-katex.tar.gz
        chmod +x mdbook-katex
        sudo ln -s $PWD/mdbook-katex /usr/local/bin/mdbook-katex
    - name: Install mdbook-inpage-tab
      shell: bash
      run: |
        mkdir -p mdbook-inpage-tab
        cd mdbook-inpage-tab
        curl -L https://github.com/shinolab/mdbook-inpage-tab/releases/download/v0.2.0/mdbook-inpage-tab-v0.2.0-x86_64-unknown-linux-gnu.tar.gz -o mdbook-inpage-tab.tar.gz
        tar -xvf mdbook-inpage-tab.tar.gz
        chmod +x mdbook-inpage-tab
        sudo ln -s $PWD/mdbook-inpage-tab /usr/local/bin/mdbook-inpage-tab
