name: Document

on:
  push:

jobs:
  check-cs:
    name: doc-check-sample-cs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            samples/cs/Program.cs
            samples/cs/AUTD3Sharp-Sample.csproj
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: build
        run: |
          dotnet build samples/cs/AUTD3Sharp-Sample.csproj -c:Release
        if: steps.changed-files.outputs.any_changed == 'true'

  check-cpp:
    name: doc-check-sample-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            samples/cpp/main.cpp
            samples/cpp/CMakeLists.txt
      - name: build
        run: |
          cd samples/cpp
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12
          cmake --build .
        if: steps.changed-files.outputs.any_changed == 'true'

  check-python:
    name: doc-check-sample-python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps: 
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            samples/python/main.py
      - name: install deps
        run: |
          python3 -m pip install --upgrade pyautd3
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: build
        run: |
          cd samples/python
          echo a | python3 main.py || true
        if: steps.changed-files.outputs.any_changed == 'true'

  check-jp:
    name: doc-check-jp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.rs
            src/codes/Users_Manual/**/*.rs
            thirdparties/Cargo.toml
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable'
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Test book jp
        run: |
          python3 build.py test jp
        if: steps.changed-files.outputs.any_changed == 'true'

  check-en:
    name: doc-check-en
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.rs
            src/codes/Users_Manual/**/*.rs
            thirdparties/Cargo.toml
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable'
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Test book en
        run: |
          python3 build.py test en
        if: steps.changed-files.outputs.any_changed == 'true'

  build:
    name: build-doc
    needs: [check-cs, check-cpp, check-python, check-jp, check-en]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build book
        run: |
          MDBOOK_BOOK__src=src/en mdbook build --dest-dir book/en
          MDBOOK_BOOK__src=src/jp mdbook build --dest-dir book/jp
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
          force_orphan: true
