name: Document

on:
  push:
    branches:
      - 'main'

jobs:
  check-cs:
    name: doc-check-sample-cs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.cs
            src/codes/Users_Manual/**/*.cs
            tools/cs_test.py
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: test codes
        run: |
          pip install joblib requests
          cd tools
          python3 cs_test.py 
        if: steps.changed-files.outputs.any_changed == 'true'

  check-cpp:
    name: doc-check-sample-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.cs
            src/codes/Users_Manual/**/*.cs
            tools/cpp_test.py
      - name: build
        run: |
          sudo apt-get update
          sudo apt-get -y install libeigen3-dev
          pip install joblib requests
          cd tools
          python3 cpp_test.py 
        if: steps.changed-files.outputs.any_changed == 'true'

  check-python:
    name: doc-check-sample-python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.py
            src/codes/Users_Manual/**/*.py
            tools/python_test.py
      - name: build
        run: |
          python3 -m pip install --upgrade pyautd3
          python3 -m pip install -U mypy ruff
          cd tools
          python3 python_test.py 
        if: steps.changed-files.outputs.any_changed == 'true'

  check-jp:
    name: doc-check-jp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.rs
            src/codes/Users_Manual/**/*.rs
            thirdparties/Cargo.toml
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable'
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Test book jp
        run: |
          python3 build.py test jp --init
        if: steps.changed-files.outputs.any_changed == 'true'

  check-en:
    name: doc-check-en
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            src/codes/Users_Manual/*.rs
            src/codes/Users_Manual/**/*.rs
            thirdparties/Cargo.toml
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable'
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files.outputs.any_changed == 'true'
      - name: Test book en
        run: |
          python3 build.py test en --init
        if: steps.changed-files.outputs.any_changed == 'true'

  build:
    name: build-doc
    needs: [check-cs, check-cpp, check-python, check-jp, check-en]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build book
        run: |
          MDBOOK_BOOK__src=src/en mdbook build --dest-dir book/en
          MDBOOK_BOOK__src=src/jp mdbook build --dest-dir book/jp
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
          force_orphan: true
